kind: Template
apiVersion: v1
template: spark-cluster-scc
metadata:
  name: spark-cluster-scc
labels:
  app: spark-cluster
objects:

- kind: SecurityContextConstraints
  apiVersion: v1
  metadata:
    annotations:
      kubernetes.io/description: derived from restricted, spark scc modifies the group ranges
    name: spark-cluster
  allowPrivilegedContainer: true
  priority: 9
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SYS_CHROOT
  - SETUID
  - SETGID
  runAsUser:
    type: MustRunAsRange
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
    ranges:
    - min: 2000
      max: 3000
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
