#!/bin/bash

# spark likes to be able to lookup a username for the running UID, if
# no name is present fake it.

# move over the existing /etc/passwd into our temp
cat /etc/passwd > ${NSS_WRAPPER_PASSWD}
cat /etc/group > ${NSS_WRAPPER_GROUP}
#echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:$SPARK_HOME:/bin/false" >> ${NSS_WRAPPER_PASSWD}

# add the user name to the last line; will always be /opt/spark (due to launch)
echo "$(id -u):x:$(id -u):$(id -g):$(id -u):$SPARK_HOME:/bin/false" >> ${NSS_WRAPPER_PASSWD}
#     ${USER_NAME}:x:${USER_ID}:${GROUP_ID}:${USER_NAME}:${HOME}:/bin/bash

export LD_PRELOAD=libnss_wrapper.so

exec "$@"
